version: "3.9"
services:
  umbrella:
    image: "nrel/api-umbrella:0.15.1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./umbrella/db:/opt/api-umbrella/var/db
      - ./umbrella/log:/opt/api-umbrella/var/log
      - ./umbrella/config:/etc/api-umbrella

  # https://docs.directus.io/guides/installation/docker/
  database:
    container_name: database
    image: postgres:12
    volumes:
      - ./state/directus/data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.53
    ports:
      - 8055:8055
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: 'OHNOESKEY'
      SECRET: 'OHNOESSECRET'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'admin@wifisess.gov'
      ADMIN_PASSWORD: 'admin@wifisess.gov'

networks:
  directus:
